## Markov Chain Simulation

This notebook calculates the stationary distribution of markov chain.

Watch video: [YouTube](https://youtu.be/i3AkTO9HLXo?list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV)

### A Delicious Markov Chain
<div align="center">
    <img src="chain.png" width="500px" height="300px">
</div>

In [3]:
# Burger: 0, Pizza: 1, Hotdog: 2
state = {
    0: 'Burger',
    1: 'Pizza',
    2: 'Hotdog'
}

### Transition Matrix
$$A=\begin{bmatrix}
{0.2}&{0.6}&{0.2}\\
{0.3}&{0}&{0.7}\\
{0.5}&{0}&{0.5}\\
\end{bmatrix}$$
$$A_{ij}=P(X_n=j|X_{n-1}=i)$$

In [2]:
import numpy as np

In [3]:
A = np.array([[0.2, 0.6, 0.2], [0.3, 0.0, 0.7], [0.5, 0.0, 0.5]])
print(A)

[[0.2 0.6 0.2]
 [0.3 0.  0.7]
 [0.5 0.  0.5]]


Bacially, a stationary distribution satisfies the following matrix equation
$$\pi A=\pi$$
If a markov chain is not stationary, the limiting state probability doesn't exist.

### Random Walk on Markov Chain

In [13]:
n = 10
start_state = 0
current_state = start_state
print(state[current_state], '->', end=' ')

while n - 1:
    current_state = np.random.choice([0, 1, 2], p=A[current_state])
    print(state[current_state], '->', end=' ')
    n -= 1
print('stop')

Burger -> Pizza -> Hotdog -> Hotdog -> Hotdog -> Hotdog -> Burger -> Pizza -> Hotdog -> Hotdog -> stop


### Approach 1: Monte Carlo

In [22]:
steps = 1e4
start_state = 0
current_state = start_state
pi = np.array([0, 0, 0])
pi[start_state] = 1
i = 0
while i < steps:
    current_state = np.random.choice([0, 1, 2], p=A[current_state])
    pi[current_state] += 1
    i += 1
print(f'\u03C0 = {pi / steps}')

π = [0.3492 0.2131 0.4378]


### Approach 2: Repeated Matrix Multiplication

In [29]:
steps = 1e4
An = A
i = 0
while i < steps:
    An = np.matmul(An, A)
    i += 1
print(f'\u03C0 = {An[0]}')

π = [0.35211268 0.21126761 0.43661972]


### Approach 3: Finding Left Eigen Vectors
In order to solve the equation $\pi A=\pi$, a method called `scipy.linalg.eig` should be used.

The eigenvalue problem is to determine the solution to the equation $Av = \lambda v$, where $A$ is an n-by-n matrix, $v$ is a column vector of length $n$, and $\lambda$ is a scalar. The values of $\lambda$ that satisfy the equation are the eigenvalues. The corresponding values of $v$ that satisfy the equation are the right eigenvectors. The left eigenvectors, $w$, satisfy the equation $w^TA = \lambda w^T$. In this problem, the eigenvector corresponding to $\lambda=1$ is the limiting state probability.

In [23]:
import scipy.linalg
D, W = scipy.linalg.eig(A, left=True, right=False)
idx = np.squeeze(np.argwhere(np.isclose(np.real(D), 1)))

In [24]:
print(D)

[ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [25]:
print(W)

[[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]]


In [31]:
# find the eigenvectors where D = 1
pi = W[:, idx]
pi_normalized = np.real(pi / np.sum(pi))
print(pi_normalized)

[0.35211268 0.21126761 0.43661972]
